config/routes.rb
Rails.application.routes.draw do
  root :to => 'searches#new'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :users
  resources :colors
  resources :pages
  resources :cars
  resources :account_types
  resources :vehicle_statuses
  resources :towns
  resources :car_types
  resources :fuel_types
  resources :gearboxes
  resources :vehicle_status
  resources :number_of_owners
  resources :manufacturers
  resources :models
  resources :searches


  get 'cars/update_models' , :as => 'update_models' 
  get '/search' => 'searches#advanced'
  get '/home' => 'cars#home'
  get '/admin' => 'cars#index'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/vehicle_statuses_controller.rb
class VehicleStatusesController < ApplicationController
  before_action :set_vehicle_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /vehicle_statuses
  # GET /vehicle_statuses.json
  def index
    @vehicle_statuses = VehicleStatus.all
  end

  # GET /vehicle_statuses/1
  # GET /vehicle_statuses/1.json
  def show
  end

  # GET /vehicle_statuses/new
  def new
    @vehicle_status = VehicleStatus.new
  end

  # GET /vehicle_statuses/1/edit
  def edit
  end

  # POST /vehicle_statuses
  # POST /vehicle_statuses.json
  def create
    @vehicle_status = VehicleStatus.new(vehicle_status_params)

    respond_to do |format|
      if @vehicle_status.save
        format.html { redirect_to @vehicle_status, notice: 'Vehicle status was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_status }
      else
        format.html { render :new }
        format.json { render json: @vehicle_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_statuses/1
  # PATCH/PUT /vehicle_statuses/1.json
  def update
    respond_to do |format|
      if @vehicle_status.update(vehicle_status_params)
        format.html { redirect_to @vehicle_status, notice: 'Vehicle status was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_status }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_statuses/1
  # DELETE /vehicle_statuses/1.json
  def destroy
    @vehicle_status.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_statuses_url, notice: 'Vehicle status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_status
      @vehicle_status = VehicleStatus.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vehicle_status_params
      params.require(:vehicle_status).permit(:name) 
    end
end

app/helpers/vehicle_statuses_helper.rb
module VehicleStatusesHelper
end

app/views/vehicle_statuses/_form.html.erb
<%= form_with(model: vehicle_status, local: true) do |form| %>
  <% if vehicle_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_status.errors.count, "error") %> prohibited this vehicle_status from being saved:</h2>

      <ul>
        <% vehicle_status.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_statuses/edit.html.erb
<h1>Editing Vehicle Status</h1>

<%= render 'form', vehicle_status: @vehicle_status %>

<%= link_to 'Show', @vehicle_status %> |
<%= link_to 'Back', vehicle_statuses_path %>

app/views/vehicle_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Statuses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_statuses.each do |vehicle_status| %>
      <tr>
        <td><%= link_to 'Show', vehicle_status %></td>
        <td><%= link_to 'Edit', edit_vehicle_status_path(vehicle_status) %></td>
        <td><%= link_to 'Destroy', vehicle_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle Status', new_vehicle_status_path %>

app/views/vehicle_statuses/new.html.erb
<h1>New Vehicle Status</h1>

<%= render 'form', vehicle_status: @vehicle_status %>

<%= link_to 'Back', vehicle_statuses_path %>

app/views/vehicle_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vehicle_status_path(@vehicle_status) %> |
<%= link_to 'Back', vehicle_statuses_path %>