config/routes.rb
Rails.application.routes.draw do
  root :to => 'searches#new'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :users
  resources :colors
  resources :pages
  resources :cars
  resources :account_types
  resources :vehicle_statuses
  resources :towns
  resources :car_types
  resources :fuel_types
  resources :gearboxes
  resources :vehicle_status
  resources :number_of_owners
  resources :manufacturers
  resources :models
  resources :searches


  get 'cars/update_models' , :as => 'update_models' 
  get '/search' => 'searches#advanced'
  get '/home' => 'cars#home'
  get '/admin' => 'cars#index'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/fuel_types_controller.rb
class FuelTypesController < ApplicationController
  before_action :set_fuel_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /fuel_types
  # GET /fuel_types.json
  def index
    @fuel_types = FuelType.all
  end

  # GET /fuel_types/1
  # GET /fuel_types/1.json
  def show
  end

  # GET /fuel_types/new
  def new
    @fuel_type = FuelType.new
  end

  # GET /fuel_types/1/edit
  def edit
  end

  # POST /fuel_types
  # POST /fuel_types.json
  def create
    @fuel_type = FuelType.new(fuel_type_params)

    respond_to do |format|
      if @fuel_type.save
        format.html { redirect_to @fuel_type, notice: 'Fuel type was successfully created.' }
        format.json { render :show, status: :created, location: @fuel_type }
      else
        format.html { render :new }
        format.json { render json: @fuel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fuel_types/1
  # PATCH/PUT /fuel_types/1.json
  def update
    respond_to do |format|
      if @fuel_type.update(fuel_type_params)
        format.html { redirect_to @fuel_type, notice: 'Fuel type was successfully updated.' }
        format.json { render :show, status: :ok, location: @fuel_type }
      else
        format.html { render :edit }
        format.json { render json: @fuel_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fuel_types/1
  # DELETE /fuel_types/1.json
  def destroy
    @fuel_type.destroy
    respond_to do |format|
      format.html { redirect_to fuel_types_url, notice: 'Fuel type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fuel_type
      @fuel_type = FuelType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fuel_type_params
      params.require(:fuel_type).permit(:name) 
    end
end

app/helpers/fuel_types_helper.rb
module FuelTypesHelper
end

app/views/fuel_types/_form.html.erb
<%= form_with(model: fuel_type, local: true) do |form| %>
  <% if fuel_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fuel_type.errors.count, "error") %> prohibited this fuel_type from being saved:</h2>

      <ul>
        <% fuel_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fuel_types/edit.html.erb
<h1>Editing Fuel Type</h1>

<%= render 'form', fuel_type: @fuel_type %>

<%= link_to 'Show', @fuel_type %> |
<%= link_to 'Back', fuel_types_path %>

app/views/fuel_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fuel Types</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fuel_types.each do |fuel_type| %>
      <tr>
        <td><%= link_to 'Show', fuel_type %></td>
        <td><%= link_to 'Edit', edit_fuel_type_path(fuel_type) %></td>
        <td><%= link_to 'Destroy', fuel_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fuel Type', new_fuel_type_path %>

app/views/fuel_types/new.html.erb
<h1>New Fuel Type</h1>

<%= render 'form', fuel_type: @fuel_type %>

<%= link_to 'Back', fuel_types_path %>

app/views/fuel_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fuel_type_path(@fuel_type) %> |
<%= link_to 'Back', fuel_types_path %>