config/routes.rb
Rails.application.routes.draw do
  root :to => 'searches#new'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :users
  resources :colors
  resources :pages
  resources :cars
  resources :account_types
  resources :vehicle_statuses
  resources :towns
  resources :car_types
  resources :fuel_types
  resources :gearboxes
  resources :vehicle_status
  resources :number_of_owners
  resources :manufacturers
  resources :models
  resources :searches


  get 'cars/update_models' , :as => 'update_models' 
  get '/search' => 'searches#advanced'
  get '/home' => 'cars#home'
  get '/admin' => 'cars#index'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gearbox.rb
class Gearbox < ApplicationRecord
    has_many :cars
end

app/controllers/gearboxes_controller.rb
class GearboxesController < ApplicationController
  before_action :set_gearbox, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  
  # GET /gearboxes
  # GET /gearboxes.json
  def index
    @gearboxes = Gearbox.all
  end

  # GET /gearboxes/1
  # GET /gearboxes/1.json
  def show
  end

  # GET /gearboxes/new
  def new
    @gearbox = Gearbox.new
  end

  # GET /gearboxes/1/edit
  def edit
  end

  # POST /gearboxes
  # POST /gearboxes.json
  def create
    @gearbox = Gearbox.new(gearbox_params)

    respond_to do |format|
      if @gearbox.save
        format.html { redirect_to @gearbox, notice: 'Gearbox was successfully created.' }
        format.json { render :show, status: :created, location: @gearbox }
      else
        format.html { render :new }
        format.json { render json: @gearbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gearboxes/1
  # PATCH/PUT /gearboxes/1.json
  def update
    respond_to do |format|
      if @gearbox.update(gearbox_params)
        format.html { redirect_to @gearbox, notice: 'Gearbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @gearbox }
      else
        format.html { render :edit }
        format.json { render json: @gearbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gearboxes/1
  # DELETE /gearboxes/1.json
  def destroy
    @gearbox.destroy
    respond_to do |format|
      format.html { redirect_to gearboxes_url, notice: 'Gearbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gearbox
      @gearbox = Gearbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gearbox_params
      params.require(:gearbox).permit(:name) 
    end
end

app/helpers/gearboxes_helper.rb
module GearboxesHelper
end

app/views/gearboxes/_form.html.erb
<%= form_with(model: gearbox, local: true) do |form| %>
  <% if gearbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gearbox.errors.count, "error") %> prohibited this gearbox from being saved:</h2>

      <ul>
        <% gearbox.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gearboxes/edit.html.erb
<h1>Editing Gearbox</h1>

<%= render 'form', gearbox: @gearbox %>

<%= link_to 'Show', @gearbox %> |
<%= link_to 'Back', gearboxes_path %>

app/views/gearboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gearboxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gearboxes.each do |gearbox| %>
      <tr>
        <td><%= link_to 'Show', gearbox %></td>
        <td><%= link_to 'Edit', edit_gearbox_path(gearbox) %></td>
        <td><%= link_to 'Destroy', gearbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gearbox', new_gearbox_path %>

app/views/gearboxes/new.html.erb
<h1>New Gearbox</h1>

<%= render 'form', gearbox: @gearbox %>

<%= link_to 'Back', gearboxes_path %>

app/views/gearboxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_gearbox_path(@gearbox) %> |
<%= link_to 'Back', gearboxes_path %>