config/routes.rb
Rails.application.routes.draw do
  root :to => 'searches#new'
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }
  resources :users
  resources :colors
  resources :pages
  resources :cars
  resources :account_types
  resources :vehicle_statuses
  resources :towns
  resources :car_types
  resources :fuel_types
  resources :gearboxes
  resources :vehicle_status
  resources :number_of_owners
  resources :manufacturers
  resources :models
  resources :searches


  get 'cars/update_models' , :as => 'update_models' 
  get '/search' => 'searches#advanced'
  get '/home' => 'cars#home'
  get '/admin' => 'cars#index'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
    mount_uploader :image_url, ImageUploader

    belongs_to :user
    belongs_to :model
    belongs_to :car_type
    belongs_to :vehicle_status
    belongs_to :number_of_owner
    belongs_to :fuel_type
    belongs_to :gearbox
    belongs_to :color
    has_many :images
end

app/models/car_type.rb
class CarType < ApplicationRecord
    has_many :cars
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :show ]
  before_action :authenticate_admin!, only: [:index]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])
  end

  # GET /cars/new
  def new
    @car = current_user.cars.build
    @manufacturers = Manufacturer.all
    @models = []
    if params[:manufacturer].present?
      @models = Manufacturer.find(params[:manufacturer]).models
    end
    if request.xhr?
      respond_to do |format|
        format.json {
          render json: {models: @models}
        }
      end
    end
  end

  def home
    @cars = Car.all
    @cars = @cars.where(user_id: current_user.id)
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:user_id, :model_id, :name, :car_type_id, :vehicle_status_id, :has_warranty, :has_guarranty, :oldtimer, :first_registration, :manufacture_year, :inspection_expiry, :mileage, :number_of_owner_id, :vin, :price, :cash_discount, :last_price, :driveable, :damaged, :crashed, :service_book, :slovenian, :garaged, :never_crashed, :fuel_type_id, :gearbox_id, :power, :ccm, :doors, :seats, :color_id, :metallic, :consumption, :abs, :fourwheel, :airbags, :xenon, :led, :automatic_lights, :alarm, :headup, :emergency_brake, :ac, :digital_ac, :keyless_go, :start_stop, :cruise_control, :electric_parking_brake, :cd_player, :mp3_player, :usb, :dab, :navigation, :rear_camera, :towing_hook, :hill_assist, :pdc, :comment, :avaliable, :image_url, :image_url_cache)
    end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/edit.html.erb
<% if (current_user.id == @car.user_id || current_user.admin?) %>
<div class="container p-0">
    <div class="container bg-white rounded-bottom shadow-box m-0 mb-3">
            <div class="row pt-3 pb-2 px-3">
                <div class="col-12 px-0">
                    <h3 class="blue"><strong>Urejanje oglasa</strong></h3>
                </div>
            </div>
    </div>
<%= render 'form', car: @car %>

<% else %>

<% end %>

app/views/cars/home.html.erb
<div class="container p-0">
        <div class="container bg-white rounded-bottom shadow-box m-0 mb-3">
            <div class="row pt-3 pb-2 px-3">
                <div class="col-12 px-0">
                    <h3 class="blue"><strong>Vaši oglasi</strong></h3>
                    <%= stylesheet_link_tag 'search' %>
                </div>
            </div>
        </div>
        

        <div class="col-12">

            <% if @cars.empty? %>
                <div class="alert-danger"><p>No cars were found.</p></div>
            <% else %>
            <% @cars.each do |car| %>
            
                        
            <div class="row bg-white mb-3 pb-3 pb-sm-0 position-relative results-row center shadow-dark text-center">

                <%= link_to car_path(car), class: "stretched-link" do %> <% end %>

                <div
                    class="bg-dark col-12 px-3 py-2 font-weight-bold text-truncate text-white text-decoration-none results-title">
                    <%= car.model.manufacturer.name %> <%= car.model.name %> <%= car.name %></div>

                <div class="col-auto px-3 py-0 py-sm-3 pt-3 photo d-flex justify-content-center align-items-center m-auto">

                    <div class="photo-display align-self-center">

                        <%= image_tag car.image_url.url, class: "img-fluid" %>

                    </div>

                </div>

                <div class="col-auto py-0 results-top-data pb-lg-3 mt-md-0 mt-md-3 mr-sm-0 pr-0 m-auto">

                    <div class="p-0 m-0 pl-3 pr-3">

                        <div class="results-top-data-display">

                            <table
                                class="table table-striped table-sm table-borderless font-weight-normal  my-3 my-sm-0">

                                <tbody>

                                    <tr>

                                        <td class="w-25 d-none d-md-block pl-3">1.registracija</td>
                                        <td class="w-75 pl-3">
                                            <%= car.first_registration.strftime('%m/%d/%Y') %></td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Prevoženih</td>
                                        <td class="pl-3"><%= car.mileage %> km</td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Gorivo</td>
                                        <td class="pl-3"><%= car.fuel_type.name %></td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Menjalnik</td>
                                        <td class="pl-3"><%= car.gearbox.name %></td>

                                    </tr>
                                    <tr class="d-none d-md-table-row">

                                        <td class="d-none d-md-block pl-3">Motor</td>
                                        <td class="pl-3">
                                            <%= car.ccm %>ccm, <%= car.power %>kW / <%= (car.power*1.34102209).round %> KM                                        </td>

                                    </tr>

                                </tbody>

                            </table>

                        </div>

                    </div>

                    <div class="mt-5 mt-sm-0 pt-0 pt-sm-5 results-price-logo">


                        <div class="results-price ml-4 ml-sm-0 ml-md-4">

                            <div class="price-show">

                                <div class="price-text">

                                    <%= number_with_delimiter(car.price, :delimiter => '.') %> €
                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>
            
        <% end %>
        <% end %>
        </div>
    </div>

app/views/cars/index.html.erb
<div class="container p-0">
    <div class="row bg-white rounded-bottom shadow-box pt-3 pb-2 m-0 mb-3">
        <div class="col-12">
            <h4>Admin panel</h4>
        </div>
    </div>

    <div class="container my-3 pb-2 bg-white shadow-box rounded">
        <div class="row pt-3">

            <div class="col-sm-4 col-12">
                <%= link_to "/users", class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje uporabnikov</span>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= link_to towns_path, class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje mest</span>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= link_to manufacturers_path, class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje znamk</span>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= link_to models_path, class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje modelov</span>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= link_to colors_path, class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje barv</span>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= link_to car_types_path, class: "btn btn-lg btn-block orange-bg text-center py-0 mb-3 text-white" do %>
                    <span class="px-3 py-2 text-center">Urejanje tipov</span>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/cars/new.html.erb
<% if user_signed_in? %>
    <% if current_user.address? && current_user.seller_title? && current_user.phone? && current_user.email? %>
        <div class="container p-0">

            <div class="container bg-white rounded-bottom shadow-box m-0 mb-3">
                    <div class="row pt-3 pb-2 px-3">
                        <div class="col-12 px-0">
                            <h3 class="blue"><strong>Dodajanje novega oglasa</strong></h3>
                        </div>
                    </div>
            </div>

        <%= render 'form', car: @car %>
    <% else %>
        <%= controller.redirect_to root_path, notice: "Preden lahko objavite oglase morate dopolniti vaše podatke!" %>
    <% end %>
<% else %>

<% end %>

app/views/cars/results.html.erb
<div class="container p-0">
        <div class="container bg-white rounded-bottom shadow-box m-0 mb-3">
            <div class="row pt-3 pb-2 px-3">
                <div class="col-12 px-0">
                    <h3 class="blue"><strong>Rezultati iskanja</strong></h3>
                    <%= stylesheet_link_tag 'search' %>
                </div>
            </div>
        </div>
        

        <div class="col-12">

            <% if @cars.empty? %>
                <div class="alert-danger"><p>No cars were found.</p></div>
            <% else %>
            <% @cars.each do |car| %>
            
                        
            <div class="row bg-white mb-3 pb-3 pb-sm-0 position-relative results-row center shadow-dark text-center">

                <%= link_to car_path(car), class: "stretched-link" do %> <% end %>

                <div
                    class="bg-dark col-12 px-3 py-2 font-weight-bold text-truncate text-white text-decoration-none results-title">
                    <%= car.model.manufacturer.name %> <%= car.model.name %> <%= car.name %></div>

                <div class="col-auto px-3 py-0 py-sm-3 pt-3 photo d-flex justify-content-center align-items-center m-auto">

                    <div class="photo-display align-self-center">

                        <%= image_tag car.image_url.url, class: "img-fluid" %>

                    </div>

                </div>

                <div class="col-auto py-0 results-top-data pb-lg-3 mt-md-0 mt-md-3 mr-sm-0 pr-0 m-auto">

                    <div class="p-0 m-0 pl-3 pr-3">

                        <div class="results-top-data-display">

                            <table
                                class="table table-striped table-sm table-borderless font-weight-normal  my-3 my-sm-0">

                                <tbody>

                                    <tr>

                                        <td class="w-25 d-none d-md-block pl-3">1.registracija</td>
                                        <td class="w-75 pl-3">
                                            <%= car.first_registration.strftime('%m/%d/%Y') %></td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Prevoženih</td>
                                        <td class="pl-3"><%= car.mileage %> km</td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Gorivo</td>
                                        <td class="pl-3"><%= car.fuel_type.name %></td>

                                    </tr>
                                    <tr>

                                        <td class="d-none d-md-block pl-3">Menjalnik</td>
                                        <td class="pl-3"><%= car.gearbox.name %></td>

                                    </tr>
                                    <tr class="d-none d-md-table-row">

                                        <td class="d-none d-md-block pl-3">Motor</td>
                                        <td class="pl-3">
                                            <%= car.ccm %>ccm, <%= car.power %>kW / <%= (car.power*1.34102209).round %> KM                                        </td>

                                    </tr>

                                </tbody>

                            </table>

                        </div>

                    </div>

                    <div class="mt-5 mt-sm-0 pt-0 pt-sm-5 results-price-logo">


                        <div class="results-price ml-4 ml-sm-0 ml-md-4">

                            <div class="price-show">

                                <div class="price-text">

                                    <%= number_with_delimiter(car.price, :delimiter => '.') %> €
                                </div>

                            </div>

                        </div>

                    </div>

                </div>

            </div>
            
        <% end %>
        <% end %>
        </div>
    </div>